### ISSUE TITLE
Can not load 

### ISSUE THREAD

**Issue by jcoyne** [cbeer/kaminari_route_prefix#6]
```
/home/travis/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- kaminari_route_prefix/actionview/action_view_extension (LoadError)
	from /home/travis/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/travis/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/travis/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.0/gems/kaminari_route_prefix-0.1.0/lib/kaminari_route_prefix.rb:17:in `<module:KaminariRoutePrefix>'
	from /home/travis/.rvm/gems/ruby-2.4.0/gems/kaminari_route_prefix-0.1.0/lib/kaminari_route_prefix.rb:13:in `<top (required)>'
```

is this line: https://github.com/cbeer/kaminari_route_prefix/blob/master/lib/kaminari_route_prefix.rb#L17
supposed to be `require 'kaminari_route_prefix/helpers/action_view_extension'` instead?

**Comment by cbeer** [comment]
Yes, I think you're right.
